version: 2.1
context: gcp_context
jobs:
  build:
    docker:
      - image: circleci/python:3.9.4
    working_directory: ~/app

    steps:
      - checkout

# Install Google Cloud SDK
      - run:
          name: Install Google Cloud SDK
          command: |
            export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk

 # Configure Google Cloud SDK
      - run:
          name: Configure Google Cloud SDK
          command: |
            echo $SERVICE_ACCOUNT_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_ID
            gcloud auth configure-docker

# Build and push Docker image
      - run:
          name: Build and push Docker image
          command: |
            docker build -t gcr.io/PROJECT_ID/node-app:latest .
            docker push gcr.io/PROJECT_ID/node-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
