orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2


jobs:
  deploy-userbackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-userbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.49.0.245 './first-deployment.sh';
        

  deploy-eventbackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-eventbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.49.0.245 './second-deployment.sh';


  deploy-servicebackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-servicebackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.49.0.245 './third-deployment.sh';
  

version: 2.1
workflows:
  build_and_deploy_sequentially:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: loadtesting-service-backend
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup
      - deploy-servicebackend-load:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup
                         
      - aws-ecr/build-and-push-image:
          name: event-backend-image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: loadtesting-event-backend
          skip-when-tags-exist: false
          tag: 'latest1,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup
      - deploy-eventbackend-load:
          requires:
            - event-backend-image
            - deploy-servicebackend-load
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup

      - aws-ecr/build-and-push-image:
          name: user-backend-image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: loadtesting-user-backend
          skip-when-tags-exist: false
          tag: 'latest2,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup
      - deploy-userbackend-load:
          requires:
            - user-backend-image
            - deploy-eventbackend-load
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup

