version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build-and-push:
          context: gcp
      - deploy-on-private-machine:
          requires:
            - build-and-push

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/my-image:$CIRCLE_SHA1 .
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud auth configure-docker
            docker push gcr.io/$GOOGLE_PROJECT_ID/my-image:$CIRCLE_SHA1

      - store_artifacts:
          path: ./gcloud-service-key.json
          destination: gcp

  deploy-on-private-machine:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - add_ssh_keys:
          fingerprints:
            - "YOUR_PRIVATE_MACHINE_SSH_KEY_FINGERPRINT"

      - run:
          name: Pull and Deploy Docker Image
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud compute ssh YOUR_PRIVATE_MACHINE_USERNAME@YOUR_PRIVATE_MACHINE_IP --project=$GOOGLE_PROJECT_ID --zone=$GOOGLE_PROJECT_ZONE --command="docker pull gcr.io/$GOOGLE_PROJECT_ID/my-image:$CIRCLE_SHA1 && docker run -d -p 8080:8080 gcr.io/$GOOGLE_PROJECT_ID/my-image:$CIRCLE_SHA1"