version: 2.1
context: gcp_context
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest 

    steps:
      - checkout

 # Configure Google Cloud SDK
      - run:
          name: Configure Google Cloud SDK
          command: |
            echo $SERVICE_ACCOUNT_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $PROJECT_ID
            gcloud auth configure-docker

# Build and push Docker image
      - run:
          name: Build and push Docker image
          command: |
            docker build -t gcr.io/PROJECT_ID/node-app:latest .
            docker push gcr.io/PROJECT_ID/node-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
