orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2
  queue: eddiewebb/queue@volatile


jobs:

  deploy-userbackend-load-US:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-userbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.51.238.191 './node-userbackend-us-ssh.sh';
        

  deploy-eventbackend-load-US:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-eventbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.51.238.191 './node-eventbackend-us-ssh.sh';


  deploy-servicebackend-load-US:
    machine:
      enabled: true
    steps:
      - queue/until_front_of_line:
          job-regex: ^DeployStep[0-9]$
          only-on-branch: circleci-project-setup
          time: '10'
      - run:
          name: deploy-servicebackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.51.238.191 './node-servicebackend-us-ssh.sh';


  deploy-userbackend-load-EU:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-userbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.51.238.191 './node-userbackend-eu-ssh.sh';
        

  deploy-eventbackend-load-EU:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-eventbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.51.238.191 './node-eventbackend-eu-ssh.sh';


  deploy-servicebackend-load-EU:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-servicebackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@13.51.238.191 './node-servicebackend-eu-ssh.sh';


version: 2.1
workflows:
  version: 2


  build_and_deploy-userload-EU:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Build-And-Push-Image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-project-setup
          requires:
            - Deployment-approval
      - Deployment-approval:
           type: approval
           filters:
             branches:
               only: circleci-project-setup
      - deploy-userbackend-load-EU:
          requires:
            - Build-And-Push-Image
          filters:
            branches:
              only: circleci-project-setup
                         

  build_and_deploy-eventload-EU:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Build-And-Push-Image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-project-setup
          requires:
            - Deployment-approval
      - Deployment-approval:
           type: approval
           filters:
             branches:
               only: circleci-project-setup
      - deploy-eventbackend-load-EU:
          requires:
            - Build-And-Push-Image
          filters:
            branches:
              only: circleci-project-setup


  build_and_deploy-serviceload-EU:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Build-And-Push-Image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-project-setup
          requires:
            - Deployment-approval
      - Deployment-approval:
           type: approval
           filters:
             branches:
               only: circleci-project-setup
      - deploy-servicebackend-load-EU:
          requires:
            - Build-And-Push-Image
          filters:
            branches:
              only: circleci-project-setup

  build_and_deploy-userload-US:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Build-And-Push-Image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-project-setup
          requires:
            - Deployment-approval
      - Deployment-approval:
           type: approval
           filters:
             branches:
               only: circleci-project-setup
      - deploy-userbackend-load-US:
          requires:
            - Build-And-Push-Image
          filters:
            branches:
              only: circleci-project-setup
                         

  build_and_deploy-eventload-US:
    jobs:
      - aws-ecr/build-and-push-image:
          name: Build-And-Push-Image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-project-setup
          requires:
            - Deployment-approval
      - Deployment-approval:
           type: approval
           filters:
             branches:
               only: circleci-project-setup
      - deploy-eventbackend-load-US:
          requires:
            - Build-And-Push-Image
          filters:
            branches:
              only: circleci-project-setup


  build_and_deploy-serviceload-US:
    jobs:
      - queue/block_workflow:
          only-on-branch: circleci-project-setup
          time: '10'
      - aws-ecr/build-and-push-image:
          name: Build-And-Push-Image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-project-setup
          requires:
            - Deployment-approval
      - Deployment-approval:
           type: approval
           filters:
             branches:
               only: circleci-project-setup
      - deploy-servicebackend-load-US:
          requires:
            - Build-And-Push-Image
          filters:
            branches:
              only: circleci-project-setup



      


  

