orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2

           

version: 2.1
workflows:
  build_and_deploy_dev:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Env/Dev/Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION
          repo: cast_data_collector_dev
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+)+(\.[0-9]+)/

      - deployment-approval:
          type: approval
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+)+(\.[0-9]+)/


              
              

