orbs:
  docker: circleci/docker@2.2.0
  gcp-gcr: circleci/gcp-gcr@0.15.1
  gcp-cli: circleci/gcp-cli@3.1.0
version: 2.1
context: gcp_context
jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.9.4  

    steps:
      - checkout

 # Configure Google Cloud SDK
      - run:
          name: Configure Google Cloud SDK
          command: |
            docker build -t gcr.io/PROJECT_ID/node-app:latest .
            echo ${SERVICE_ACCOUNT_KEY} | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            docker login -u _json_key --password-stdin https://us-east4-docker.pkg.dev/prod-healthsafe/healthvault-prod < ${HOME}/gcloud-service-key.json
            docker push gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:${CIRCLE_SHA1}
            gcloud config set project $PROJECT_ID
            gcloud auth configure-docker us-east4-docker.pkg.dev
            docker push gcr.io/PROJECT_ID/node-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_push
