orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2

jobs:

  deploy-servicebackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-servicebackend
          command: ssh ec2-user@16.16.28.38 './third-deployment.sh';

  deploy-eventbackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-eventbackend
          command: ssh ec2-user@16.16.28.38 './second-deployment.sh';

  deploy-userbackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-userbackend
          command: ssh ec2-user@16.16.28.38 './first-deployment.sh';
      
  
version: 2.1
workflows:
  build_and_deploy_sequentially:
    jobs:

      - aws-ecr/build-and-push-image:
          name: Service-backend-image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup

      - deploy-servicebackend-load:
          requires:
            - Service-backend-image
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup

                 
      - aws-ecr/build-and-push-image:
          name: Event-backend-image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest1,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup
      - deploy-eventbackend-load:
          requires:
            - Event-backend-image
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup

      - aws-ecr/build-and-push-image:
          name: User-backend-image
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: testing-repo
          skip-when-tags-exist: false
          tag: 'latest2,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup

      - deploy-userbackend-load:
          requires:
            - User-backend-image
          filters:
            branches:
              only: circleci-editor/923/circleci-project-setup

