version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build-and-push:
          context: gcp
      - deploy-on-private-machine:
          requires:
            - build-and-push

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $PROJECT_URL/node_app -f ./Dockerfile .
            docker tag $PROJECT_URL/node_app $PROJECT_URL/node_app:latest
            cat $GCLOUD_SERVICE_ACCOUNT | docker login -u  _json_key --password-stdin https://us-east4-docker.pkg.dev/prod-healthsafe/healthvault-prod
            gcloud auth activate-service-account --key-file=$GCLOUD_SERVICE_ACCOUNT
            gcloud beta auth configure-docker us-east4-docker.pkg.dev
            docker push $PROJECT_URL/node_app:latest

  deploy-on-private-machine:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "YOUR_PRIVATE_MACHINE_SSH_KEY_FINGERPRINT"

      - run:
          name: Pull and Deploy Docker Image
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            ssh -o StrictHostKeyChecking=no newam@${INTERNAL_IP}  "ls"
            gcloud compute ssh YOUR_PRIVATE_MACHINE_USERNAME@YOUR_PRIVATE_MACHINE_IP --project=$GOOGLE_PROJECT_ID --zone=$GOOGLE_PROJECT_ZONE --command="./ohif-backend.sh"