orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@2.0.2



jobs:
  deploy-userbackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-userbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@139.16.67.74 './node-userbackend-ssh.sh';
        

  deploy-eventbackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-eventbackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@139.16.67.74 './node-eventbackend-ssh.sh';


  deploy-servicebackend-load:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy-servicebackend
          command: ssh -o StrictHostKeyChecking=no ec2-user@139.16.67.74 './node-servicebackend-ssh.sh';
  



version: 2.1
workflows:
  build_and_deploy-serviceload:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Env/Load/ServiceDockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: loadtesting-service-backend
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: feature/LoadTestEnhancement
      - deploy-servicebackend-load:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: feature/LoadTestEnhancement
                         

  build_and_deploy-eventload:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Env/Load/EventDockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: loadtesting-event-backend
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: feature/LoadTestEnhancement
      - deploy-eventbackend-load:
          requires:
            - aws-ecr/build-and-push-image
            - build_and_deploy-serviceload
          filters:
            branches:
              only: feature/LoadTestEnhancement
              
              
  build_and_deploy-userload:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          create-repo: true
          dockerfile: Env/Load/UserDockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION_load
          repo: loadtesting-user-backend
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: feature/LoadTestEnhancement
      - deploy-userbackend-load:
          requires:
            - aws-ecr/build-and-push-image
            - build_and_deploy-eventload
          filters:
            branches:
              only: feature/LoadTestEnhancement
